name: netgeek
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  injectable: ^1.5.3
  google_fonts: ^4.0.4
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^7.0.1
  pretty_dio_logger: ^1.1.1
  share_plus: ^6.3.1
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  shared_preferences: ^2.0.17
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  freezed: ^2.3.2
  flutter_lints: ^2.0.0
  drift_dev: ^2.5.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/config/
